FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@10.32.1 --activate

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

EXPOSE 3000
CMD ["pnpm", "dev"]
