services:
    # 인증용 임시 저장소 (Redis)
    redis:
        image: redis:alpine
        container_name: seoganpyo-redis
        ports:
            - "6379:6379"

    # FastAPI 백엔드
    backend:
        build: .
        container_name: seoganpyo-api
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        env_file:
            - .env
        # 아래처럼 .env의 변수명을 맞춰주세요.
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis